### ISSUE TITLE
CAR setup queries_TJ Kotze

### ISSUE THREAD

**Issue by GitGud93** [Waztom/xchem-CAR#48]
For unlocking secrets in Gitcrypt i'm having some trouble identifying which repository my CAR clone is in. How do I identify where the clone is located so as to unlock secrets?

**Comment by Waztom** [comment]
Hello - when you clone the repo it will be saved in a directory called "xchem-CAR". To find the directoyr - in a Linux terminal, try:
`find ~ -type d -name "xchem-CAR"`

For the git-crypt part - you need the PATH to the repo

**Comment by GitGud93** [comment]
Thanks I did exactly as stated and it worked great!
