### ISSUE TITLE
Time to launch file not found error when executing makemigrations

### ISSUE THREAD

**Issue by GitGud93** [Waztom/xchem-CAR#51]
File not found error for the directory logs, which is not what was created according to the instructions (mkdir log). I'm assuming that upon running the python migration script(not sure what this does yet, haven't read up on the commands) it looks for the directory we created to place things in but is looking for a 'logs' directory while we created a 'log' directory? Is this true or am i misunderstanding things? 

![image](https://user-images.githubusercontent.com/88319231/128177186-d2d4726f-d6ff-4377-81e5-f6e076bdf640.png)

**Comment by Waztom** [comment]
Oh shoot - sorry, the instruction in the README should be (have updated):

`mkdir log && cd log && touch logsfile.log`  

What is happening, is that you've created the log directory correctly but created the 'logsfile.log' in the 'workspace/CAR' directory. You can cd into the log directory at 'workspace/CAR/log' and create the logsfile.log using `touch logsfile.log`.

**Comment by GitGud93** [comment]
Thanks, though I think the readme is still incorrect as i got the same error. I've changed the code to 
mkdir logs && cd log && touch logfile.log 

Which didn't cause an error and matches up with the directory required. Running the manage and make migrations code now doesn't return an error however it does return 'No changes detected' is this correct?
