### ISSUE TITLE
Test Reactions on OT.

### ISSUE THREAD

**Issue by MathewGolding** [Waztom/xchem-CAR#77]
To get the user Dani and recent starter Mathew used to the CAR and OpenTrons prior to the large scale experimentation, some simple test reactions to get them used to the robot is undertaken.

- [x] Create CAR protocol for amidation test reagents
- [x] Amidation reactions
- [x] Make standard for LCMS
- [x] Run LCMS
- [x] Learn how to view data from LCMS
- [x] Run 1 uL of T3P in 100 uL of standard on LCMS to see if the peaks we are seeing are consistent with degradation of T3P
- [x] Checked that the amidation reactions worked
- [x] Check the reagents necessary for the Schotten-Baumann test reaction
- [x] Find reagents in the lab
- [x] Create CAR protocol for Sulfonamide Schotten-Baumann test reagents
- [x] Sulfonamide Schotten-Baumann reactions
- [x] Run LCMS
- [x] Checked that the sulfonamide Schotten-Baumann reactions worked
- [x] Reran amdiations using HATU, HBTU, and HCTU
- [x] Run LCMS
- [x] Checked that the amdiations using HATU, HBTU, and HCTU reactions worked

**Comment by Waztom** [comment]
@MathewGolding please see https://chemrxiv.org/engage/chemrxiv/article-details/641ef81e647e3dca997c2ba6 for more details re Sulfonamide Schotten-Baumann reaction.

**Comment by MathewGolding** [comment]
@Waztom Please put the Sulfonamide schotten-bauman reactions through the CAR to generate protocols for the OTs when possible, so I can prepare and execute the experiment asap
