### ISSUE TITLE
Make first Scarab entry

### ISSUE THREAD

**Issue by Waztom** [Waztom/xchem-CAR#78]
@MathewGolding please try creating your first ELN entry in Scarab for the amidation test. 

Suggest you use a hypothesis driven approach with headings:

1. H&S checklist
    - COSHH complete
    - Risk assessments complete
    - Waste streams identified 
2. Hypothesis
4. Experimental details (this section will need refinement)
    - Materials used
    - Experimental details - (what, when, why)
5. Results
6. Conclusion

**Comment by MathewGolding** [comment]
making the scarab for both the amidation and sulfonamide reactions in one document. It will cut down on the file number for these test reactions and both are types of amide synthesis so it is fitting and comparisons between the successful reactions can be made.
