### ISSUE TITLE
Setup CAR dev environment

### ISSUE THREAD

**Issue by Waztom** [Waztom/xchem-CAR#80]
Mathew needs a local version of CAR running to see code and test the system on his machine.  

Please see https://github.com/Waztom/fragalysis-devcontainer for instructions to set a development container/environment up.

**Comment by MathewGolding** [comment]
Hit a wall, need assistance

**Comment by MathewGolding** [comment]
Might be worth creating a github on the following?
- [ ] How to use combichem as part of CAR
- [ ] How to use Plate IDs to get the SMILES data and what data set each well was a part of
